# Generated by Django 5.1.3 on 2024-11-14 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_class_name', models.CharField(max_length=255)),
                ('predicted_class_index', models.IntegerField()),
                ('predictions', models.JSONField()),
                ('image_url', models.URLField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_searchhistory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
